name: example-environment
channels:
  - conda-forge
dependencies:
  - ase
  - python
  - pyiron
  - pyiron_base
  - lammps
  - nglview
  - pyscal
  - jupyterlab
  - pyiron-data >=0.0.5
  - pip:
      - jupyterlab_latex
