name: MD_melting
channels:
  - conda-forge
dependencies:
  - numpy
  - pandas
  - nodejs
  - pyscal
  - pyiron_base
  - ase
  - python
  - lammps
  - nglview
  - jupyterlab
  - pip:
      - jupyterlab_latex
